---
title: "R的编程风格"
author: "李峰"
date: "2019年4月"
output:
  html_document: 
    number_sections: yes
    theme: lumen
    toc: yes
    toc_depth: 5
---


---


# 文件名



## 好的

fit-models.R   
utility-functions.R   

## 差的

foo.r   
stuff.r   


## 如果文件需要顺序执行

0-download.R   
1-parse.R   
2-explore.R   




# 变量和函数名

+ 小写
+ 用下划线将单词分开
+ 变量是名词
+ 函数是动词
+ 不要和已有函数重名


## 好的

day_one
day_1


## 差的

first_day_of_the_month   
DayOne   
dayone   



# 语法


## 空格的使用

### 中缀运算符前后使用空格

#### 好的

average <- mean(feet / 12 + inches, na.rm = TRUE)   

#### 差的

average<-mean(feet/12+inches,na.rm=TRUE)   



### :, :: and ::: 不需要加空格

#### 好的
x <- 1:10   
base::get   

#### 差的
x <- 1 : 10   
base :: get   



### 逗号的后面而非前面加空格，小括号的左边加空格

#### 好的

if (debug) do(x)   
plot(x, y)   

#### 差的

if(debug)do(x)   
plot (x, y)   


### 为了对齐可以使用多个空格


list(   
  total = a + b + c,    
  mean  = (a + b + c) / n   
)   


### 小括号或中括号内代码两侧无需空格


#### 好的

if (debug) do(x)   
diamonds[5, ]   


#### 差的


if ( debug ) do(x)     
x[1,]      
x[1 ,]     



## 大括号的使用

+ 大括号的左半边不能单独一行
+ 大括号的左半边后必须另起一行
+ 大括号的右半边必须单独一行或紧跟else


### 好的


if (y < 0 && debug) {   
  message("Y is negative")   
}   
   
if (y == 0) {   
  log(x)   
} else {   
  y ^ x   
}   


### 差的


if (y < 0 && debug)   
message("Y is negative")   

if (y == 0) {   
  log(x)   
}    
else {   
  y ^ x   
}   


### 可以在一行留下非常短的句子


if (y < 0 && debug) message("Y is negative)"


# 行的长度

+ 每行不超过80个字符


# 缩进

+ 使用两个空格表示缩进，不使用制表符
+ 定义函数时，第二行如果需要缩进，缩进到定义开始的地方。


# 赋值

赋值使用 <- 而非 =


## 好的

x <- 5

## 差的

x = 5




# 注释


+ 注释应以注释符和空格开始
+ 使用 - 或者 = 构成的注释行构成分割线将代码切为容易理解的段落


```{r}
# Load data ---------------------------

# Plot data ---------------------------
```







   



















